name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build & push Docker image
        uses: docker/build-push-action@v1
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}
          registry: rg.fr-par.scw.cloud
          repository: tthsympa/home
          tags: latest
          build_args: PORT=${{ secrets.PORT }}

  deploy:
    name: Deploy Docker image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy & run throught SSH
        uses: fifsky/ssh-action@v0.0.4
        with:
          command: |
            docker login ${{ env.SCW_REGISTRY }}/tthsympa -u nologin -p ${{ env.SCW_SECRET_TOKEN }}
            docker pull rg.fr-par.scw.cloud/tthsympa/home:latest
            docker run -d -p ${{ env.HOME_PORT }}:${{ env.HOME_PORT }} tthsympa/home:latest
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
