name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: nologin
          password: ${{ secrets.TTHSYMPA_SCW_SECRET_KEY }}
          registry: rg.fr-par.scw.cloud

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: rg.fr-par.scw.cloud/tthsympa/home:latest
      - run: docker push rg.fr-par.scw.cloud/tthsympa/home:latest

  deploy:
    name: Deploy Container
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        run: |
          curl -X POST -H 'X-Auth-Token: ${{ secrets.TTHSYMPA_SCW_SECRET_KEY }}' 'https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/82ccaa10-4f27-4c75-af3b-d86620f83fb0/deploy' -d '{}'

